@startuml
|Руководитель|
start
    :Создать эталон метрики, привязать к листу, лист к должности и периоду;
    :Запустить период;
|Система|
    :Создать факты метрик для всех пользователей (статус "Новая");
    :Заблокировать эталон метрики;
|Пользователь|
    :Заполнить факт метрики (статус "Изменено");
    repeat
        :Редактировать значение факта метрики;
        :Отправить на согласование (статус "На согласование");
|Руководитель|
        :Проверить метрику;
        if (Метрика согласована?) then (да)
            :Установить статус "Согласовано";
        else (нет)
            :Вернуть пользователю (статус "Требует изменения");
|Пользователь|
        endif
    repeat while (Пользователь меняет метрику)
@enduml
