@startuml
set separator none
title FastMBO — Контекст

left to right direction

!include <C4/C4>
!include <C4/C4_Context>

System(FastMBO, "FastMBO", $descr="Система управления мотивацией персонала.", $tags="", $link="")
Person(Сотрудник, "Сотрудник", $descr="Заполняет и просматривает оценочные листы, достижения и метрики.", $tags="", $link="")
Person(Заместительдиректора, "Заместитель директора", $descr="Согласует достижения и метрики подчинённых.", $tags="", $link="")
Person(Директор, "Директор", $descr="Управляет периодами, утверждает результаты, контролирует фонд премирования.", $tags="", $link="")
Person(Администраторсистемы, "Администратор системы", $descr="Администрирование, настройки, аудит.", $tags="", $link="")

Rel(Сотрудник, FastMBO, "Заполнение и просмотр оценочных листов, достижений, метрик", $techn="", $tags="", $link="")
Rel(Заместительдиректора, FastMBO, "Согласование достижений/метрик подчинённых", $techn="", $tags="", $link="")
Rel(Директор, FastMBO, "Управление периодами, утверждение результатов, контроль фонда", $techn="", $tags="", $link="")
Rel(Администраторсистемы, FastMBO, "Администрирование, настройки, аудит", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml